# https://github.com/marketplace/actions/eleventy-action

name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20']
        
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}